[project]
name = "benson"
version = "0.1.0"
authors = ["Krv Analytics <team@krv.ai>"]
description = "A multiverse data cleaning tool for agent pickup."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.2.3",
    "pytest>=8.3.5",
    "scikit-learn>=1.6.1",
]
