name: website

# build the documentation whenever there are new commits on main
on:
  push:
    branches:
      - docs

# security: restrict permissions for CI jobs.
permissions:
  contents: read

jobs:
  # Build the documentation and upload the static HTML files as an artifact.
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      # ADJUST THIS: install all dependencies (including pdoc)
      - run: python -m pip install uv
      - run: uv sync
      - run: source .venv/bin/activate
      - run: pdoc --d numpy benson benson.imputation benson.magic --logo https://krv.ai/images/logo/logo-light.svg -o docs/api

      - uses: actions/upload-pages-artifact@v3
        with:
          path: docs/api

  # Deploy the artifact to GitHub pages.
  # This is a separate job so that only actions/deploy-pages has the necessary permissions.
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
